[package]
name = "verysimplex"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.1"
num-traits = "0.2.19"
tabled = "0.16.0"

[target.'cfg(target_os = "macos")'.dependencies]
nalgebra-lapack = { version = "0.25.0", default-features = false, features = [
    "accelerate",
] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
nalgebra-lapack = { version = "0.25.0", default-features = false, features = [
    "openblas",
] }
